name: GitActions Demo1
on: push
jobs:
  GitActions-demo-job:
    name: Demo Job
    runs-on: ubuntu-latest
    steps:
      - name: Print a environment
        env:
          MY_VAR: Hi there! My Name is
          FRIST_NAME: wonyoung
          LAST_NAME: kim
          AWS_JOB_NAME: kim.wy
      run: |
        echo $MY_VAR $FIRST_NAME $LAST_NAME.
        echo $MY_VAR $AWS_JOB_NAME.
